CREATE TABLE IF NOT EXISTS empresa.clientes(
DNI VARCHAR(11) NOT NULL,
NOMBRE VARCHAR(100) NULL,
DIRECCION VARCHAR(150),
BARRIO VARCHAR(50),
CIUDAD VARCHAR(50),
ESTADO VARCHAR(10),
CP VARCHAR(10),
FECHA_NACIMIENTO DATE,
EDAD SMALLINT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUMEN_COMPRA FLOAT,
PRIMERA_COMPRA BIT(1),
PRIMARY KEY(DNI)
);

CREATE TABLE IF NOT EXISTS empresa.vendedores(
MATRICULA VARCHAR(5) NOT NULL,
NOMBRE VARCHAR(100) NULL,
BARRIO VARCHAR(50),
COMISION FLOAT,
FECHA_ADMISION DATE,
VACACIONES BIT(1),
PRIMARY KEY(MATRICULA)
);

CREATE TABLE IF NOT EXISTS empresa.productos(
CODIGO VARCHAR(10) NOT NULL,
DESCRIPCION VARCHAR(100) NULL,
SABOR VARCHAR(50),
TAMAÑO VARCHAR(50),
ENVASE VARCHAR(50),
PRECIO FLOAT,
PRIMARY KEY(CODIGO)
);

CREATE TABLE IF NOT EXISTS facturas(
NUMERO VARCHAR(5) NOT NULL,
FECHA DATE NULL,
DNI VARCHAR(11) NOT NULL,
MATRICULA VARCHAR(5) NOT NULL,
IMPUESTO FLOAT,
PRIMARY KEY(NUMERO),
FOREIGN KEY(DNI) REFERENCES empresa.clientes(DNI),
FOREIGN KEY(MATRICULA) REFERENCES empresa.vendedores(MATRICULA)
);

CREATE TABLE IF NOT EXISTS empresa.items(
NUMERO VARCHAR(5) NOT NULL,
CODIGO VARCHAR(10) NOT NULL,
CANTIDAD INT,
PRECIO FLOAT,
PRIMARY KEY(NUMERO, CODIGO),
FOREIGN KEY(NUMERO) REFERENCES empresa.facturas(NUMERO),
FOREIGN KEY(CODIGO) REFERENCES empresa.productos(CODIGO)
);